### ISSUE TITLE
NameError: global name ‘dump_sql_statement’ is not defined

### ISSUE THREAD

**Issue by gauravdalvi63** [seanharr11/etlalchemy#17]
.
.
.
.
ETLAlchemySource (INFO) - Creating 'upsert' statements for '3' rows, and dumping to 'demo_tags_sum.sql'.
ETLAlchemySource (INFO) - Creating 'insert' stmts for (the remaining)3 rows, and dumping to 'demo_tags_sum.sql' (because they DNE in the table!).
ETLAlchemySource (INFO) -  (3) -- Inserting remaining '3' rows.
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    migrate()
  File "app.py", line 10, in migrate
    tgt.migrate(migrate_fks=False, migrate_indexes=True, migrate_data=  True, migrate_schema=True)
  File "/usr/local/lib/python2.7/site-packages/etlalchemy/ETLAlchemyTarget.py", line 86, in migrate
    migrate_data=migrate_data)
  File "/usr/local/lib/python2.7/site-packages/etlalchemy/ETLAlchemySource.py", line 1117, in migrate
    pks, Session)
  File "/usr/local/lib/python2.7/site-packages/etlalchemy/ETLAlchemySource.py", line 846, in dump_data
    dump_sql_statement(
NameError: global name '**dump_sql_statement**' is not defined

**Comment by seanharr11** [comment]
@gauravdalvi63 I have this fixed in commit https://github.com/seanharr11/etlalchemy/commit/33a8b62f0c023d7883e3a714ac895bb41aa4e2e3

Nice find! Clearly the project is lacking regression tests, as my last release seemingly broke the *upsert* operation.

The function name should have been *dump_to_sql_statement*, I have renamed accordingly.

If you install the project from github here, you will see the fix. I will bundle this fix, along with a few others, into the next release, end eventually get it up onto PyPi (so you can install from pip with this fix)

Thanks again!
